- CMakeLists.txt
Back to enable the soversion. It was reverted in 53c81ac0cf8ca1884bfc3aa7c1de847ad4b25934
> Restore SOVERSION

- .travis.yml
- CMakeLists.txt
- src/console.cpp
This package uses only a small amount of boost
for a mutex and scoped_lock.
These are replaced with std::mutex
and std::lock_guard from c++11.
Boost is removed as a dependency
and the c++11 compiler flag is added.
> Use c++11 instead of boost

- src/console.cpp
Use `fopen_s` instead of `fopen` on Windows, and check the error code.
Closes #32.
> Fix windows compiler warning

- appveyor.yml
Compiling and running the tests on Visual Studio 2013/2015. 
AppVeyor need to be enabled by the repo maintainers at https://www.appveyor.com . 
Example run at : https://ci.appveyor.com/project/traversaro/console-bridge/build/job/g1swcad37ab6v6p5 . 
Currently failing for https://github.com/ros/console_bridge/issues/34 .
> Add appveyor CI to test regressions on Windows

- appveyor.yml
- test/CMakeLists.txt
Fixes the Windows build.
Closes #34.
Waiting to make sure that appveyor is enabled.
> MSVC disable -Wno-deprecated-declarations

- CMakeLists.txt
- appveyor.yml
- test/CMakeLists.txt
* Keep binaries and dll in the same build directory to avoid path issues.
* Shamelessly copied the strategy from https://github.com/robotology/yarp/blob/aa779bdf3056d90a04acaf8d96dfc09100e960b9/conf/YarpOptions.cmake#L14 .
* This is also convenient to use a library directly from the build directory. 
* Don't use the full path of the test binary in add_test . 
* CMake will automatically expand a target to the full path ( `If <command> specifies an executable target (created by add_executable()) it will automatically be replaced by the location of the executable created at build time.` https://cmake.org/cmake/help/v3.0/command/add_test.html ). 
* Re-enable tests on AppVeyor .
> Fix tests on Windows

- CMakeLists.txt
- console_bridge-config.cmake.in
See discussion in https://github.com/ros/console_bridge/issues/44 .
> Make CMake configuration files relocatable 

- test/CMakeLists.txt
Linking against pthread isn't needed on Android.
> Don't link against pthread on Android

- CMakeLists.txt
To get rid of the warning: http://ci.ros2.org/job/ci_osx/3164/warnings2Result/new/
Result with this patch: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3166)](http://ci.ros2.org/job/ci_osx/3166/)
> explicitly enable CMake policy 42 to prevent warning

- test/CMakeLists.txt
This is related to https://github.com/ros2/ros2/issues/743
I think `tf2` is running into conflicts when using console bridge from homebrew ([v.0.4.3](https://github.com/Homebrew/homebrew-core/blob/0e28f3d23854ecca30cb3eeea80e949da348186f/Formula/console_bridge.rb#L4)) vs the version installed by the ros2 `console_bridge_vendor` package ([v.0.4.1](https://github.com/ros2/console_bridge_vendor/blob/d3be808a1b77028a152a8ee5aa56346ce32db987/CMakeLists.txt#L54)). 
My believe is that setting the global include directories for gtest might cause the trouble where an inconsistent state between library of `ament_cmake_gtest` and the `console_bridge` gtest headers occurs. 
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
> use target include directories for gtest

- CMakeLists.txt
This bumps the minimum CMake version to 3.0.2, which is the [minimum supported by ROS Kinetic](https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) and new enough to default to the NEW behavior of [CMP0048](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html). This avoids a CMake warning when building and testing this package in Debian Buster and Ubuntu Focal.
Signed-off-by: ahcorde <ahcorde@gmail.com>
> [noetic] Bump CMake version to avoid CMP0048 warning

- CONTRIBUTING.md
- LICENSE
- QUALITY_DECLARATION.md
- README.md
Quality Declaration document for libconsole-bridge-dev library, declaring this library as category level 4 for its use within the ROS2 ecosystem.
Signed-off-by: Jorge J. Perez <jjperez@ekumenlabs.com>
> Quality Declaration, License and Contributing files

- include/console_bridge/console.h
When compiling `console_bridge` with `clang`, I get the following warnings:
```
In file included from /vol/sandbox/ros2/src/srdfdom/src/model.cpp:38:
/opt/ros/dashing/include/console_bridge/console.h:67:90: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
console_bridge::log(__FILE__, __LINE__, console_bridge::CONSOLE_BRIDGE_LOG_ERROR, fmt, ##__VA_ARGS__)
```
> fix clang warnings

- test/console_TEST.cc
I wrote the following test while reviewing #64 but added it to a separate pull request to keep things simple.
On my machine it prints:
~~~
[ RUN      ] ConsoleTest.MultipleArguments
Error:   no extra parameters
at line 32 in /Users/scpeters/clone/console_bridge/test/console_TEST.cc
Error:   one integer: 42
at line 33 in /Users/scpeters/clone/console_bridge/test/console_TEST.cc
Error:   two floats: 42.010000, 0.33
at line 34 in /Users/scpeters/clone/console_bridge/test/console_TEST.cc
[       OK ] ConsoleTest.MultipleArguments (0 ms)
~~~
> Add test for macros with multiple arguments

- README.md
- test/console_TEST.cc
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
This just adds in basic tests for all of the functions in console.h.  I'm not going to claim that it gives 100% test coverage, but it at least gives us basic confidence that things are working.
> Add in tests.

- QUALITY_DECLARATION.md
- test/console_TEST.cc
As the title says, this is to target Quality Level 1 for this library as defined in [REP-2004](https://www.ros.org/reps/rep-2004.html). I wasn't sure who to tag in the copyright notice, so I'm open to change it accordingly.
As this library does not check automatically copyright notices, I added an extra line to the Quality Level document stating that new files will require having it.
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
> Add copyright notice for testing file

- QUALITY_DECLARATION.md
- README.md
As the title says, missing information is added to the QD of the package.
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
> Update QD to match Quality Level 2

- test/console_TEST.cc
It looks like OutputFileHandler was the only feature that is not currently tested in this package. This adds a test for that, and also basic stdout/stderr smoke tests.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Add tests for OutputFileHandler

- test/CMakeLists.txt
part of the work done for QNX support https://github.com/ros2/ros2/issues/988
> removes -lpthread when building for QNX

- test/CMakeLists.txt
to fix eg:
```
3/3 Test #3: console_bridge_cpplint3/3 Test #3: console_bridge_cpplint............***Failed    0.15 sec
…/src/console_bridge-1.0.2/include/console_bridge/console.h:37:  #ifndef header guard has wrong style, please use: SRC_CONSOLE_BRIDGE_1_0_2_INCLUDE_CONSOLE_BRIDGE_CONSOLE_H_  [build/header_guard] [5]
…/src/console_bridge-1.0.2/include/console_bridge/console.h:192:  #endif line should be "#endif  // SRC_CONSOLE_BRIDGE_1_0_2_INCLUDE_CONSOLE_BRIDGE_CONSOLE_H_"  [build/header_guard] [5]
> Provide PROJECT_SOURCE_DIR to cpplint
